In [1]:
import pandas as pd
import numpy as np

In [2]:
order_items = pd.read_csv('olist_order_items_dataset.csv')

In [3]:
order_items.head(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

In [4]:
order_items.shape

(112650, 7)

In [5]:
# check duplicates
order_items = order_items.drop_duplicates()

In [6]:
order_items.shape

(112650, 7)

In [7]:
# check nulls
order_items.isna().sum()
# no nulls

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [8]:
# check data types
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [9]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [10]:
order_items['average_prices'] = order_items.groupby('product_id')['price'].transform('mean').round(2)
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,average_prices
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,59.23
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,239.90
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,199.00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,202.40
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,291.19
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,355.00
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,93.16
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,55.90
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,43.00

In [11]:
price_Q1 = order_items['price'].quantile(0.25)
price_Q3 = order_items['price'].quantile(0.75)

In [12]:
price_IQR = price_Q3 - price_Q1
price_lower_bound = price_Q1 - 1.5 * price_IQR
price_Upper_bound = price_Q3 + 1.5 * price_IQR

In [13]:
price_lower_bound

np.float64(-102.6)

In [14]:
price_Upper_bound

np.float64(277.4)

In [15]:
price_upper_limit = order_items['price'].quantile(0.95)
price_upper_limit

np.float64(349.9)

In [16]:
price_lower_limit = order_items['price'].quantile(0.5)
price_lower_limit

np.float64(74.99)

In [17]:
order_items.shape

(112650, 8)

In [18]:
price_outliers = order_items[(order_items['price'] < price_lower_bound) |(order_items['price'] > price_Upper_bound)]
price_outliers

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,average_prices
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75,810.00
16,0009c9a17f916a706d71784483a5d643,1,3f27ac8e699df3d300ec4a5d8c5cf0b2,fcb5ace8bcc92f75707dc0f01a27d269,2018-05-02 09:31:53,639.00,11.34,639.00
26,0011d82c4b53e22e84023405fb467e57,1,c389f712c4b4510bc997cee93e8b1a28,bfd27a966d91cfaafdb25d076585f0da,2018-01-29 21:51:25,289.00,26.33,285.67
30,00137e170939bba5a3134e2386413108,1,672e757f331900b9deea127a2a7b79fd,e59aa562b9f8076dd550fcddf0e73491,2017-11-30 06:30:55,397.00,24.65,405.00
39,0017afd5076e074a48f1f1a4c7bac9c5,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-04-24 22:25:19,809.10,44.29,762.01
...,...,...,...,...,...,...,...,...
112586,ffdc5e3279114c523a09296f8fd28331,1,5e70a4508abd5d19bfe7f110785294c8,328acb143b4a73aad6bee8e734f5d20d,2017-02-14 14:49:23,299.99,17.80,299.99
112592,ffde92ba447b33a47d1c04d203f10f41,1,a97cd00f5c1dbfbc7f0f4b6c1032253e,b347677812ea483b0f528eaf8cbc09b7,2017-11-30 14:13:18,278.00,26.70,292.00
112632,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.00,20.91,736.00
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,291.19
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,355.00

In [19]:
price_outliers[price_outliers['product_id'] == 'fe59a1e006df3ac42bf0ceb876d70969']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,average_prices
39,0017afd5076e074a48f1f1a4c7bac9c5,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-04-24 22:25:19,809.1,44.29,762.01
21319,30cb9807736cf9827533cf34b10969d8,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-05-25 20:02:23,809.1,40.18,762.01
21320,30cb9807736cf9827533cf34b10969d8,2,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-05-25 20:02:23,809.1,40.18,762.01
31260,46e8348ff73e64f24843a7d2fad9fcfd,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-03-23 09:10:18,809.1,31.16,762.01
38994,589eac637e68da58add10ee5e6710bac,2,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2018-01-18 02:31:48,599.0,49.61,762.01
40766,5cd63812f35304841de07758daef7b4c,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-08-02 22:50:11,787.9,36.27,762.01
46447,698c554458e6b44e6f2f1450583c2547,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-06-12 02:32:26,790.9,36.29,762.01
52613,77b85146fc12a34dd81ef54524f247b2,2,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-11-28 02:47:02,700.9,82.99,762.01
63585,9125faac1b379b7b9ab4665189739e31,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-05-26 13:15:15,809.1,36.41,762.01
73487,a77e640490c0930838454624780038b5,1,fe59a1e006df3ac42bf0ceb876d70969,3bb548e3cb7f70f28e3f11ee9dce0e59,2017-11-13 04:30:32,709.9,33.37,762.01
76192,ad7d812f43f6308a7105fecab91fe3c1,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-05-19 02:51:00,809.1,52.16,762.01
88869,c9dff4871bed0bc5d4b917767a22d67d,2,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-11-30 11:18:26,700.9,74.66,762.01

In [20]:
price_no_outliers = order_items[(order_items['price'] >= price_lower_bound) & (order_items['price'] <= price_Upper_bound)]
price_no_outliers

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,average_prices
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,59.23
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,239.90
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,199.00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,202.40
...,...,...,...,...,...,...,...,...
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,62.15
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03,119.10
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,93.16
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,55.90
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,43.00

In [21]:
# frights outliers
frights_Q1 = order_items['freight_value'].quantile(0.25)
frights_Q3 = order_items['freight_value'].quantile(0.75)
frights_IQR = frights_Q3 - frights_Q1

In [22]:
frights_upper_bound = frights_Q1 - 1.5* frights_IQR
frights_lower_bound = frights_Q3 + 1.5*frights_IQR

In [23]:
frights_no_outliers = order_items[(order_items['freight_value'] >= frights_lower_bound) & (order_items['freight_value'] <= frights_upper_bound)]
frights_no_outliers

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, average_prices]
Index: []

no outliers

In [24]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
average_prices         0
dtype: int64

In [25]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
average_prices         float64
dtype: object

In [26]:
order_items.shape

(112650, 8)

In [27]:
order_items.drop_duplicates(inplace= True , keep= 'first')

In [28]:
order_items.shape

(112650, 8)

In [29]:
pd.DataFrame.to_csv(order_items , 'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_order_items_dataset.csv')