In [237]:
import pandas as pd
import numpy as np

In [238]:
# column names
geolocation_zip_code_prefix	= 'geolocation_zip_code_prefix'
geolocation_lat	= 'geolocation_lat'
geolocation_lng	= 'geolocation_lng'
geolocation_city = 	'geolocation_city'
geolocation_state = 'geolocation_state'

In [239]:
geolocation = pd.read_csv('olist_geolocation_dataset.csv',index_col=False)

In [240]:
sellers = pd.read_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_sellers_dataset.csv',index_col=False)
customers = pd.read_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_customers_dataset.csv',index_col=False)
order_items = pd.read_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_order_items_dataset.csv',index_col=False)
orders = pd.read_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_orders_dataset.csv',index_col=False)

In [241]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [242]:
sellers.isna().sum()

Unnamed: 0                0
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [243]:
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [244]:
geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [245]:
# check duplictes
geolocation.shape

(1000163, 5)

In [246]:
geolocation = geolocation.drop_duplicates(keep= 'first')

In [247]:
geolocation.shape

(738332, 5)

In [248]:
# check data type
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [249]:
geolocation['geolocation_lat_mean'] = geolocation.groupby('geolocation_zip_code_prefix')['geolocation_lat'].transform('mean')
geolocation['geolocation_lon_mean'] = geolocation.groupby('geolocation_zip_code_prefix')['geolocation_lng'].transform('mean')

In [250]:
geolocation.shape

(738332, 7)

In [251]:
geolocation.duplicated(geolocation_zip_code_prefix).count()

np.int64(738332)

In [252]:
geolocation.drop_duplicates(subset=geolocation_zip_code_prefix,inplace=True,keep='first')

In [253]:
geolocation.shape

(19015, 7)

In [254]:
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,geolocation_lat_mean,geolocation_lon_mean
0,1037,-23.545621,-46.639292,sao paulo,SP,-23.545335,-46.638995
1,1046,-23.546081,-46.644820,sao paulo,SP,-23.545885,-46.643744
3,1041,-23.544392,-46.639499,sao paulo,SP,-23.544036,-46.639889
4,1035,-23.541578,-46.641607,sao paulo,SP,-23.541613,-46.641583
5,1012,-23.547762,-46.635361,são paulo,SP,-23.547808,-46.634844
...,...,...,...,...,...,...,...
999774,99955,-28.107588,-52.144019,vila langaro,RS,-28.112176,-52.144629
999780,99970,-28.345143,-51.876926,ciriaco,RS,-28.343920,-51.874988
999786,99910,-27.863500,-52.084760,floriano peixoto,RS,-27.857786,-52.070728
999803,99920,-27.858716,-52.300403,erebango,RS,-27.855254,-52.300906
999846,99952,-28.160371,-51.936922,santa cecilia do sul,RS,-28.171199,-51.908569

In [255]:
geolocation.drop(columns=['geolocation_lat','geolocation_lng'],inplace=True)

In [256]:
sellers = pd.merge(sellers , geolocation ,how = 'left' , left_on= 'seller_zip_code_prefix' , right_on='geolocation_zip_code_prefix')
customers = pd.merge(customers , geolocation ,how = 'inner' , left_on= 'customer_zip_code_prefix' , right_on='geolocation_zip_code_prefix')

In [257]:
sellers.isna().sum()

Unnamed: 0                     0
seller_id                      0
seller_zip_code_prefix         0
seller_city                    0
seller_state                   0
geolocation_zip_code_prefix    7
geolocation_city               7
geolocation_state              7
geolocation_lat_mean           7
geolocation_lon_mean           7
dtype: int64

In [258]:
sellers.dropna(inplace=True)

In [259]:
sellers.drop(columns=['seller_zip_code_prefix','geolocation_city','geolocation_state'],inplace = True)
sellers.isna().sum()

Unnamed: 0                     0
seller_id                      0
seller_city                    0
seller_state                   0
geolocation_zip_code_prefix    0
geolocation_lat_mean           0
geolocation_lon_mean           0
dtype: int64

In [260]:
customers.drop(columns=['customer_zip_code_prefix','geolocation_city','geolocation_state'],inplace = True)
customers

,customer_id,customer_unique_id,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat_mean,geolocation_lon_mean
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,14409,-20.499273,-47.396658
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,9790,-23.728396,-46.542250
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,1151,-23.531309,-46.656690
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,8775,-23.500670,-46.186348
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,13056,-22.975708,-47.143140
...,...,...,...,...,...,...,...
99158,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,sao paulo,SP,3937,-23.586179,-46.499652
99159,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,taboao da serra,SP,6764,-23.616789,-46.767716
99160,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,fortaleza,CE,60115,-3.735628,-38.510775
99161,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,canoas,RS,92120,-29.949964,-51.168380
99162,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,cotia,SP,6703,-23.596649,-46.911766

In [261]:
# pd.DataFrame.to_csv(customers,'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_customers_dataset.csv',index=False)
# pd.DataFrame.to_csv(sellers,'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_sellers_dataset.csv',index=False)

In [262]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'average_prices'],
      dtype='str')

In [263]:
sellers.columns

Index(['Unnamed: 0', 'seller_id', 'seller_city', 'seller_state',
       'geolocation_zip_code_prefix', 'geolocation_lat_mean',
       'geolocation_lon_mean'],
      dtype='str')

In [264]:
order_items = pd.merge(sellers,order_items, on = 'seller_id' , how = 'left')[['order_id','order_item_id', 'product_id', 'seller_id','shipping_limit_date', 'price', 'freight_value','geolocation_lat_mean','geolocation_lon_mean']]

In [265]:
order_items.isna().sum()

order_id                0
order_item_id           0
product_id              0
seller_id               0
shipping_limit_date     0
price                   0
freight_value           0
geolocation_lat_mean    0
geolocation_lon_mean    0
dtype: int64

In [266]:
order_items.rename(columns={
'geolocation_lat_mean' : 'sellers_lat',
'geolocation_lon_mean' : 'sellers_lon'
},inplace=True)

In [267]:
orders.columns

Index(['Unnamed: 0', 'order_id', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference'],
      dtype='str')

In [268]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_city', 'customer_state',
       'geolocation_zip_code_prefix', 'geolocation_lat_mean',
       'geolocation_lon_mean'],
      dtype='str')

In [269]:
orders = pd.merge(customers,orders,on = 'customer_id',how='left')

In [270]:
orders.columns

Index(['customer_id', 'customer_unique_id', 'customer_city', 'customer_state',
       'geolocation_zip_code_prefix', 'geolocation_lat_mean',
       'geolocation_lon_mean', 'Unnamed: 0', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference'],
      dtype='str')

In [271]:
orders.drop(columns=['customer_unique_id', 'customer_city', 'customer_state', 'geolocation_zip_code_prefix'],inplace=True)

In [272]:
orders.drop(columns=['Unnamed: 0'],inplace=True)

In [273]:
orders.rename(columns={
    'geolocation_lat_mean':'customer_lat',
    'geolocation_lon_mean':'customer_lon'
},inplace=True)

In [274]:
orders.isna().sum()

customer_id                         0
customer_lat                        0
customer_lon                        0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
purchase_approved_diff              0
hours_to_approve                    0
minutes_to_approve                  0
sec_to_approve                      0
customers_carrier_difference     2957
dtype: int64

In [275]:
orders.columns

Index(['customer_id', 'customer_lat', 'customer_lon', 'order_id',
       'order_status', 'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference'],
      dtype='str')

In [276]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'sellers_lat',
       'sellers_lon'],
      dtype='str')

In [277]:
order_items = pd.merge(orders,order_items,on='order_id',how='inner')

In [278]:
order_items.isna().sum()

customer_id                         0
customer_lat                        0
customer_lon                        0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
purchase_approved_diff              0
hours_to_approve                    0
minutes_to_approve                  0
sec_to_approve                      0
customers_carrier_difference     2443
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
sellers_lat                         0
sellers_lon                         0
dtype: int64

In [279]:
order_items.columns

Index(['customer_id', 'customer_lat', 'customer_lon', 'order_id',
       'order_status', 'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'sellers_lat', 'sellers_lon'],
      dtype='str')

In [280]:
order_items.drop(columns=[])

,customer_id,customer_lat,customer_lon,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,sec_to_approve,customers_carrier_difference,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,sellers_lat,sellers_lon
0,06b8999e2fba1a1fbc88172c00ba8bc7,-20.499273,-47.396658,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,...,37,1 days 23:47:38,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,5/22/2017 15:22,124.99,21.88,-23.486138,-46.367107
1,18955e83d337fd6b2def6b18a428ac77,-23.728396,-46.542250,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,...,8,13 days 19:26:20,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,1/18/2018 20:58,289.00,46.48,-26.912506,-48.674090
2,4e7b3e00288586ebd08712fdd0374a03,-23.531309,-46.656690,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51.000000,2018-06-13,...,25,3 days 03:27:51,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,6/5/2018 16:19,139.94,17.79,-23.486138,-46.367107
3,b2b6027bc5c5109e529d4dc6358b12c3,-23.500670,-46.186348,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,...,41,0 days 16:41:43,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,3/27/2018 16:31,149.94,23.36,-23.486138,-46.367107
4,4f2d8ab171c80ec8364f7c12e35b23ad,-22.975708,-47.143140,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00.000000,2018-08-09 20:55:48,2018-08-15,...,39,10 days 05:39:48,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,7/31/2018 10:10,230.00,22.25,-21.757225,-48.829541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112091,17ddf5dd5d51696bb3d7c6291687be6f,-23.586179,-46.499652,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37.000000,2018-04-25,...,28,2 days 17:58:01,1,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,4/12/2018 16:08,74.90,13.88,-22.211504,-49.658895
112092,e7b71a9017aa05c9a7fd292d714858e8,-23.616789,-46.767716,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45.000000,2018-04-20,...,50,6 days 00:12:10,1,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,4/10/2018 8:35,114.90,14.16,-21.772215,-48.180724
112093,5e28dfe12db7fb50a4b2f691faecea5e,-3.735628,-38.510775,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17.000000,2018-05-09 19:03:15,2018-05-02,...,13,30 days 01:10:58,1,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,4/12/2018 20:30,37.00,19.04,-23.545570,-46.577968
112094,56b18e2166679b8a959d72dd06da27f9,-29.949964,-51.168380,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05,...,47,10 days 01:33:58,1,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,11/9/2017 21:15,689.00,22.07,-21.363473,-48.229588
112095,274fa6071e5e17fe303b9748641082c8,-23.596649,-46.911766,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21.000000,2017-12-26 18:42:36.000000,2018-01-08,...,16,4 days 23:25:15,1,017692475c1c954ff597feda05131d73,3c7c4a49ec3c6550809089c6a2ca9370,12/26/2017 18:50,13.99,7.78,-23.498739,-46.483079

In [281]:
def calculate_distance(lat_seller , lat_customer , lon_seller , lon_customer):
    lat_seller, lat_customer , lon_seller , lon_customer = map(np.radians , [lat_seller , lat_customer ,lon_seller ,lon_customer])
    dlat = lat_customer - lat_seller
    dlon = lon_customer - lon_seller
    a = np.sin(dlat/2)**2 + np.cos(lat_customer)* np.cos(lat_seller) *np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    # نصف قطر الأرض بالكيلومتر ~ 6371 كم
    km = 6371 * c
    return km

In [282]:
order_items['distance_km'] = order_items.apply(lambda raw: calculate_distance(
raw['sellers_lat'],
raw['customer_lat'],
raw['sellers_lon'],
raw['customer_lon']    
),axis=1)

In [283]:
order_items.dtypes

customer_id                          str
customer_lat                     float64
customer_lon                     float64
order_id                             str
order_status                         str
order_purchase_timestamp             str
order_approved_at                    str
order_delivered_carrier_date         str
order_delivered_customer_date        str
order_estimated_delivery_date        str
purchase_approved_diff               str
hours_to_approve                   int64
minutes_to_approve                 int64
sec_to_approve                     int64
customers_carrier_difference         str
order_item_id                      int64
product_id                           str
seller_id                            str
shipping_limit_date                  str
price                            float64
freight_value                    float64
sellers_lat                      float64
sellers_lon                      float64
distance_km                      float64
dtype: object

In [284]:
order_items.isna().sum()

customer_id                         0
customer_lat                        0
customer_lon                        0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
purchase_approved_diff              0
hours_to_approve                    0
minutes_to_approve                  0
sec_to_approve                      0
customers_carrier_difference     2443
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
sellers_lat                         0
sellers_lon                         0
distance_km                         0
dtype: int64

In [ ]:
# order_items.drop(columns=['sellers_lat','sellers_lon'],inplace = True)

In [286]:
order_items.dtypes

customer_id                          str
customer_lat                     float64
customer_lon                     float64
order_id                             str
order_status                         str
order_purchase_timestamp             str
order_approved_at                    str
order_delivered_carrier_date         str
order_delivered_customer_date        str
order_estimated_delivery_date        str
purchase_approved_diff               str
hours_to_approve                   int64
minutes_to_approve                 int64
sec_to_approve                     int64
customers_carrier_difference         str
order_item_id                      int64
product_id                           str
seller_id                            str
shipping_limit_date                  str
price                            float64
freight_value                    float64
distance_km                      float64
dtype: object

In [289]:
order_items.columns

Index(['customer_id', 'customer_lat', 'customer_lon', 'order_id',
       'order_status', 'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'distance_km'],
      dtype='str')

In [290]:
order_items.drop(columns=[ 'order_status', 'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'purchase_approved_diff',
       'hours_to_approve', 'minutes_to_approve', 'sec_to_approve',
       'customers_carrier_difference','customer_id'],inplace= True)

In [291]:
order_items.isna().sum()

customer_lat           0
customer_lon           0
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
distance_km            0
dtype: int64

In [292]:
pd.DataFrame.to_csv(geolocation , 'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_geolocation_dataset.csv')

In [293]:
pd.DataFrame.to_csv(order_items,'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_order_items_dataset.csv')